name = "Blue Lotus - Beyond"
author = "tazta2ra"
version = "0.5.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbdab5e7f5f361e2cf4a14a979018523b145cb1569465a4224e01bf3e7cc5fdc"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "modpack/datapacks"
