name = "Blue Lotus - Beyond"
author = "tazta2ra"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "339c2116f69c3102056e4d34d6525bbdc799c94679026b693d17d27b3d11a73f"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "modpack/datapacks"
