name = "Blue Lotus - Beyond"
author = "tazta2ra"
version = "0.5.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0acb7f097962aff981cb3bcf2032a72d073597d7977cb26bbfbf2f4259f4c827"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "modpack/datapacks"
